export const EXAMPLE = 'EXAMPLE';
export const GLOBAL_STATE_CHANGE = 'GLOBAL_STATE_CHANGE';
export const COUNTER_INC = 'COUNTER_INC';
export const COUNTER_DEC = 'COUNTER_DEC';
export const COUNTER_CHANGED = 'COUNTER_CHANGED';
export const PROFILE_STATE_CHANGE = 'PROFILE_STATE_CHANGE';
